### ISSUE TITLE
[Feature request] Make conda installable

### ISSUE THREAD

**Issue by jolespin** [metagentools/MetaCoAG#16]
Would it be possible to make this installable via bioconda or even your own channel? The environment yaml file is helpful but getting the executable in the path has to be customized for every environment it's installed in. If bioconda is not an option, can it be pip installable? The environment.yml will pick up either conda or pip dependencies.

**Comment by Vini2** [comment]
Hello @jolespin,

That is a great idea. I will work on adding a bioconda distribution for MetaCoAG in future.

Thank you!

**Comment by Vini2** [comment]
Hello @jolespin,

MetaCoAG will be available soon on bioconda. The PR at bioconda-recipes is awaiting approval. I'll let you know once it has been approved.

Thank you!

**Comment by jolespin** [comment]
Looking forward to it. Once it's on there I will add it to my metagenomics pipeline GitHub.com/jolespin/veba it's in review right now but I'll make it one of the first mods. I saved the intermediate files to use with Metacoag in the future.

**Comment by Vini2** [comment]
Hello @jolespin,

Thank you very much for using MetaCoAG in your metagenomics pipeline. MetaCoAG is now available via bioconda at [https://anaconda.org/bioconda/metacoag](https://anaconda.org/bioconda/metacoag). Let me know if you have any further questions.

Thank you!

**Comment by Vini2** [comment]
Closing issue after adding MetaCoAG to [bioconda](https://anaconda.org/bioconda/metacoag).
