### ISSUE TITLE
coverage across multiple samples for binning

### ISSUE THREAD

**Issue by franciscozorrilla** [metagentools/MetaCoAG#44]
Hello, thanks for developing this tool.

In the metacoag paper you write:

> MetaCoAG can be easily extended to work with other metagenomics assemblers. In the future, we plan to extend MetaCoAG to support overlapped binning [[24](https://link.springer.com/chapter/10.1007/978-3-031-04749-7_5#ref-CR24)] (i.e., contigs may belong to multiple species) and multi-sampled binning [[27](https://link.springer.com/chapter/10.1007/978-3-031-04749-7_5#ref-CR27)] (i.e., integration across multiple samples instead of co-assembly).

I am wondering if the current implementation of metacoag supports input coverage across multiple samples for binning?

Best,
Francisco

**Comment by Vini2** [comment]
Hi @franciscozorrilla,

Thanks for your interest in MetaCoAG.

Yes, MetaCoAG supports input coverage across multiple samples for binning. You can generate coverage files for each sample using a tool such as CoverM and combine those into one abundance file using the [`combine_cov.py`](https://github.com/metagentools/MetaCoAG/blob/develop/src/metacoag/metacoag_utils/support/combine_cov.py) script.

Please let me know if you have any further questions.

Thanks,
Vijini

**Comment by Vini2** [comment]
Closing this issue as coverage across multiple samples is already supported. Please re-open if there are further issues on this topic.

**Comment by franciscozorrilla** [comment]
Thanks for the info @Vini2 ! Will re-open if I have any issues with this.
